[package]
name = "unix-socket-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.26", features = ["rt", "rt-multi-thread", "macros", "net", "io-util"] }