name: Push test images for E2E
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  Push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Python - build and push
        uses: docker/build-push-action@v3
        with:
          context: python
          file: python/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/metalbear-co/mirrord-pytest:latest
      - name: Node - build and push
        uses: docker/build-push-action@v3
        with:
          context: node
          file: node/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/metalbear-co/mirrord-node:latest
      - name: Node UDP Logger - build and push
        uses: docker/build-push-action@v3
        with:
          context: node-udp-logger
          file: node-udp-logger/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/metalbear-co/mirrord-node-udp-logger:latest
      - name: http-logger - build and push
        uses: docker/build-push-action@v3
        with:
          context: http-logger
          file: http-logger/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/metalbear-co/mirrord-http-logger:latest
      - name: http-logger - build and push
        uses: docker/build-push-action@v3
        with:
          context: http-log-requester
          file: http-log-requester/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/metalbear-co/mirrord-http-log-requester:latest
      - name: tcp-echo - build and push
        uses: docker/build-push-action@v3
        with:
          context: tcp-echo
          file: tcp-echo/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/metalbear-co/mirrord-tcp-echo:latest
      - name: websocket - build and push
        uses: docker/build-push-action@v3
        with:
          context: websocket
          file: websocket/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/metalbear-co/mirrord-websocket:latest
      - name: unix-socket-server - build and push
        uses: docker/build-push-action@v3
        with:
          context: unix-socket-server
          file: unix-socket-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/metalbear-co/mirrord-unix-socket-server:latest
      - name: http-keep-alive - build and push
        uses: docker/build-push-action@v3
        with:
          context: http-keep-alive
          file: http-keep-alive/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/metalbear-co/mirrord-http-keep-alive:latest
      - name: sqs-forwarder - build and push
        uses: docker/build-push-action@v3
        with:
          context: sqs-forwarder
          file: sqs-forwarder/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/metalbear-co/mirrord-sqs-forwarder:latest

